# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.ones(3)

# Create a 2-dimensional NumPy array using np.array()
a2 = np.ones((2,3))

# Create a 3-dimensional Numpy array using np.array()
a3 = np.ones((3, 4, 3))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('float64'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 4, 3), 3, dtype('float64'), 36, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [12]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
range = np.arange(0, 100, 3)
range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [16]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr = np.random.randint(0, 10, size=(7,2))
rand_arr

array([[9, 4],
       [6, 6],
       [4, 9],
       [1, 4],
       [4, 5],
       [5, 3],
       [9, 5]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_bin = np.random.rand(3, 5)
rand_bin

array([[0.72074696, 0.85580779, 0.44752296, 0.07526551, 0.35536435],
       [0.22187206, 0.25245862, 0.80250445, 0.71941419, 0.26535261],
       [0.40469527, 0.58941258, 0.46563762, 0.99770029, 0.06118404]])

In [20]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_seed = np.random.randint(0, 10, size=(4,6))
rand_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [22]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
sort_rand = np.random.randint(0, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(sort_rand)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [23]:
# Find the 0'th index of the latest array you created
sort_rand[0]

array([4, 1, 3, 6, 7, 2, 0])

In [25]:
# Get the first 2 rows of latest array you created
sort_rand[:2]

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5]])

In [26]:
# Get the first 2 values of the first 2 rows of the latest array
sort_rand[:2, :2]

array([[4, 1],
       [3, 1]])

In [29]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ones2 = np.ones((3,5))
rand_array2 = np.random.randint(0, 10, size=(3,5))

In [30]:
# Add the two arrays together
ones2 + rand_array2

array([[ 4.,  8.,  7.,  9.,  8.],
       [ 5.,  2.,  5.,  8., 10.],
       [ 9.,  9.,  1.,  9.,  7.]])

In [31]:
# Create another array of ones of shape (5, 3)
ones3 = np.ones((5, 3))

In [32]:
# Try add the array of ones and the other most recent array together
rand_array2 + ones3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [37]:
# Create another array of ones of shape (3, 5)
ones4 = np.ones((3, 5))

In [38]:
# Subtract the new array of ones from the other most recent array
rand_array2 - ones4

array([[ 2.,  6.,  5.,  7.,  6.],
       [ 3.,  0.,  3.,  6.,  8.],
       [ 7.,  7., -1.,  7.,  5.]])

In [39]:
# Multiply the ones array with the latest array
rand_array2 * ones4

array([[3., 7., 6., 8., 7.],
       [4., 1., 4., 7., 9.],
       [8., 8., 0., 8., 6.]])

In [40]:
# Take the latest array to the power of 2 using '**'
rand_array2 ** 2

array([[ 9, 49, 36, 64, 49],
       [16,  1, 16, 49, 81],
       [64, 64,  0, 64, 36]], dtype=int32)

In [41]:
# Do the same thing with np.square()
np.square(rand_array2)

array([[ 9, 49, 36, 64, 49],
       [16,  1, 16, 49, 81],
       [64, 64,  0, 64, 36]], dtype=int32)

In [42]:
# Find the mean of the latest array using np.mean()
np.mean(rand_array2)

5.733333333333333

In [43]:
# Find the maximum of the latest array using np.max()
np.max(rand_array2)

9

In [44]:
# Find the minimum of the latest array using np.min()
np.min(rand_array2)

0

In [45]:
# Find the standard deviation of the latest array
np.std(rand_array2)

2.644911256650316

In [46]:
# Find the variance of the latest array
np.var(rand_array2)

6.995555555555554

In [47]:
# Reshape the latest array to (3, 5, 1)
np.reshape(rand_array2, (3, 5, 1))

array([[[3],
        [7],
        [6],
        [8],
        [7]],

       [[4],
        [1],
        [4],
        [7],
        [9]],

       [[8],
        [8],
        [0],
        [8],
        [6]]])

In [48]:
# Transpose the latest array
rand_array2.T

array([[3, 4, 8],
       [7, 1, 8],
       [6, 4, 0],
       [8, 7, 8],
       [7, 9, 6]])

What does the transpose do?

In [53]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_array3 = np.random.randint(0, 10, size=(3,3))
rand_array4 = np.random.randint(0, 10, size=(3,2))

In [54]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_array3, rand_array4)

array([[ 87,  81],
       [114, 105],
       [ 30,  42]])

In [65]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_array5 = np.random.randint(0, 10, size=(4,3))
rand_array6 = np.random.randint(0, 10, size=(4,3))

In [66]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_array5, rand_array6)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [67]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(rand_array6.T, rand_array5)

array([[ 32, 126, 122],
       [ 64, 167, 116],
       [ 40,  90,  70]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [68]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_array7 = np.random.randint(0, 10, size=(4,3))
rand_array8 = np.random.randint(0, 10, size=(4,3))

In [69]:
# Compare the two arrays with '>'
rand_array7 > rand_array8

array([[ True,  True, False],
       [False, False, False],
       [ True,  True,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [70]:
# Compare the two arrays with '>='
rand_array7 >= rand_array8

array([[ True,  True, False],
       [False, False,  True],
       [ True,  True,  True],
       [False, False, False]])

In [71]:
# Find which elements of the first array are greater than 7
rand_array7 > 7

array([[False,  True, False],
       [False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [72]:
# Which parts of each array are equal? (try using '==')
rand_array7 == rand_array8

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [82]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_array8, axis=0)

array([[1, 3, 3],
       [2, 5, 9],
       [4, 6, 9],
       [4, 9, 9]])

In [90]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_array8)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [91]:
rand_array8

array([[4, 6, 9],
       [4, 5, 9],
       [1, 3, 3],
       [2, 9, 9]])

In [94]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_array8)

2

In [93]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_array8)

6

In [95]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand_array8, axis=1)

array([2, 2, 1, 1], dtype=int64)

In [96]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(rand_array8, axis=0)

array([0, 3, 0], dtype=int64)

In [99]:
# Create an array of normally distributed random numbers
norm_array = np.random.normal(size=(3,5))
norm_array

array([[-0.98150865,  0.46210347,  0.1990597 , -0.60021688,  0.06980208],
       [-0.3853136 ,  0.11351735,  0.66213067,  1.58601682, -1.2378155 ],
       [ 2.13303337, -1.9520878 , -0.1517851 ,  0.58831721,  0.28099187]])

In [102]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0, 5, 15, dtype=int)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 5])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.